### ISSUE TITLE
App crashes 1 out 10 times on calling Jitsi.closeMeeting() function

### ISSUE THREAD

**Issue by kawaldeep2507** [gunschu/jitsi_meet#144]
https://github.com/jitsi/jitsi-meet/issues/7105

exactly this error log is coming 

`Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
at android.os.Handler.handleCallback(Handler.java:883) 
at android.os.Handler.dispatchMessage(Handler.java:100) 
at android.os.Looper.loop(Looper.java:237) 
at android.app.ActivityThread.main(ActivityThread.java:7811) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:110)
at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:126)
at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:99)
at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:223)
at java.lang.reflect.Method.invoke(Native Method) 
at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135) 
at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
at android.os.Handler.handleCallback(Handler.java:883) 
at android.os.Handler.dispatchMessage(Handler.java:100) 
at android.os.Looper.loop(Looper.java:237) 
at android.app.ActivityThread.main(ActivityThread.java:7811) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) `

i know a person has fixed this issue and fork it here
https://github.com/jitsi/jitsi-meet/pull/7961

but how can import that changes in Jitsi_meet flutter plugin locally?

`rootProject.allprojects {
    repositories {
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }

        google()
        jcenter()
    }
}
`

`dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // Jitsi Meet from https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/react/jitsi-meet-sdk   i 
    implementation ('org.jitsi.react:jitsi-meet-sdk:2.10.0') { transitive = true }

}`

**Comment by tuantvu** [comment]
@kawaldeep2507 thanks for bringing this to our attention. I prefer this plugin source from the official Jitsi releases rather than forks. Do you know if the Jitsi meet team had pushed this into their release yet? We can update the sdk when that happens.

**Comment by jimmyjose-dev** [comment]
I can confirm it has not been merged.

**Comment by jimmyjose-dev** [comment]
> but how can import that changes in Jitsi_meet flutter plugin locally?

After you have made changes locally and run the build script
add the path like this
maven { url "$rootDir/../node_modules/react-native/android" } or  full path of output directory
