### ISSUE TITLE
Crashing - FATAL EXCEPTION: mqt_native_modules 

### ISSUE THREAD

**Issue by maheshperi19** [gunschu/jitsi_meet#166]
I am getting fatal exception " FATAL EXCEPTION: mqt_native_modules" and "java.lang.ExceptionInInitializerError".

Here is the complete logs : 

E/AndroidRuntime( 6120): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 6120): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 6120): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
E/AndroidRuntime( 6120): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
E/AndroidRuntime( 6120): 	at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:51)
E/AndroidRuntime( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfigBuilder(FrescoModule.java:143)
E/AndroidRuntime( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfig(FrescoModule.java:130)
E/AndroidRuntime( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.initialize(FrescoModule.java:93)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:222)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:97)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:102)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:441)
E/AndroidRuntime( 6120): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6120): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E/AndroidRuntime( 6120): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E/AndroidRuntime( 6120): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6120): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
E/AndroidRuntime( 6120): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
E/AndroidRuntime( 6120): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
E/AndroidRuntime( 6120): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
E/AndroidRuntime( 6120): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
E/AndroidRuntime( 6120): 	... 16 more
E/JitsiMeetSDK( 6120): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 6120): java.lang.ExceptionInInitializerError
E/JitsiMeetSDK( 6120): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
E/JitsiMeetSDK( 6120): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:51)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfigBuilder(FrescoModule.java:143)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfig(FrescoModule.java:130)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.initialize(FrescoModule.java:93)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:222)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:97)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:102)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:441)
E/JitsiMeetSDK( 6120): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK( 6120): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E/JitsiMeetSDK( 6120): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E/JitsiMeetSDK( 6120): 	at java.lang.Thread.run(Thread.java:923)
E/JitsiMeetSDK( 6120): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
E/JitsiMeetSDK( 6120): 	... 16 more
E/JitsiMeetSDK( 6120):
E/JitsiMeetSDK( 6120): java.lang.ExceptionInInitializerError
E/JitsiMeetSDK( 6120): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
E/JitsiMeetSDK( 6120): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:944)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:51)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfigBuilder(FrescoModule.java:143)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfig(FrescoModule.java:130)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.modules.fresco.FrescoModule.initialize(FrescoModule.java:93)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:222)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:97)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:102)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:441)
E/JitsiMeetSDK( 6120): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK( 6120): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E/JitsiMeetSDK( 6120): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK( 6120): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E/JitsiMeetSDK( 6120): 	at java.lang.Thread.run(Thread.java:923)
E/JitsiMeetSDK( 6120): Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:370)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:204)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:178)
E/JitsiMeetSDK( 6120): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:179)
E/JitsiMeetSDK( 6120): 	... 16 more
I/Process ( 6120): Sending signal. PID: 6120 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by maheshperi19** [comment]
I have used below line in app level build.gradle file. **Currently app is not crashing**.

>  implementation 'com.squareup.okhttp3:okhttp:4.9.0'


Please confirm any one having same issue.

**Comment by jimmyjose-dev** [comment]
Does this happen in our example app too ?

**Comment by maheshperi19** [comment]
No. I didn't find this issue in example app.  After integrating into my app, i got this error. I am using connection service in android for incoming call to notify user and firebase push notifications. I am not sure it is creating that exception.

**Comment by jimmyjose-dev** [comment]
Jitsi team has advised not to use the connection service
https://github.com/jitsi/jitsi-meet/commit/95eb551156c6769e25be9855dd2bc21adf71ac76
We have mentioned this in our readme as well.

**Comment by maheshperi19** [comment]
Yes. I saw that and already disabled it by adding this line 

`featureFlag.callIntegrationEnabled = false;`

But if i am not adding below line in app level gradle file, i am getting exception.
`implementation 'com.squareup.okhttp3:okhttp:4.9.0'
`

Actually i am trying with one to one direct video calling instead of joining the user in the particular room. So that i have used call_keep flutter package to acheive incoming call to end user.

**Comment by jimmyjose-dev** [comment]
I will try to run a quick test this week, thanks for bringing this up.

**Comment by tuantvu** [comment]
@MaheshPeri19 still happening?

**Comment by maheshperi19** [comment]
@tuantvu 

Recently i haven't got this crash. I included below line in app level build.gradle file. May be the reason for not getting again

`implementation 'com.squareup.okhttp3:okhttp:4.9.0' // to avoid crashing in jitsi
`

**Comment by tuantvu** [comment]
Thanks. Maybe we will create a common fix documentation for workarounds needed.
