### ISSUE TITLE
#JitsiMeet-Flutter App crash in release mode but runs good in build mode

### ISSUE THREAD

**Issue by naveed-iqbal** [gunschu/jitsi_meet#213]
**Platform:** Android
**Device Type:** Physical
**Device Model:** Samsung J7 Pro
**Device OS Version:** Android 9
**Jitsi Meet version:** jitsi_meet: ^2.0.0

**Steps to recreate:** 
- Generate a flutter release build
- Install the app in device
- Join jitsi meeting, app will crash

...

**Error logs:** 
E/AndroidRuntime(10728): FATAL EXCEPTION: create_react_context
E/AndroidRuntime(10728): Process: care.alcela.silvercare, PID: 10728
E/AndroidRuntime(10728): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: Didn't find class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file "/data/app/care.alcela.silvercare-SnQBKma73uYdTHyX4ja60g==/base.apk"],nativeLibraryDirectories=[/data/app/care.alcela.silvercare-SnQBKma73uYdTHyX4ja60g==/lib/arm, /data/app/care.alcela.silvercare-SnQBKma73uYdTHyX4ja60g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
E/AndroidRuntime(10728): 	at com.facebook.soloader.SoLoader.a(:6)
E/AndroidRuntime(10728): 	at com.facebook.soloader.SoLoader.a(Unknown Source:104)
E/AndroidRuntime(10728): 	at com.facebook.soloader.SoLoader.a(Unknown Source:87)
E/AndroidRuntime(10728): 	at com.facebook.soloader.SoLoader.a(Unknown Source:1)
E/AndroidRuntime(10728): 	at com.facebook.react.bridge.ReactBridge.staticInit(:2)
E/AndroidRuntime(10728): 	at com.facebook.react.bridge.NativeMap.<clinit>(Unknown Source:0)
E/AndroidRuntime(10728): 	at com.facebook.react.jscexecutor.a.create(Unknown Source:0)
E/AndroidRuntime(10728): 	at c.d.m.l$b.run(Unknown Source:58)
E/AndroidRuntime(10728): 	at java.lang.Thread.run(Thread.java:764)

**Comment by naveed-iqbal** [comment]
**What I have tried so far:**
- Setup proguard rules according to sample app
- Enabled multidex
- Added lines below in proguard rules
`-keep class com.facebook.jni.** { *; }
-keep class com.facebook.react.modules.blob.BlobCollector { *; }`
But this ends up with different error log

**Comment by naveed-iqbal** [comment]
Adding lines below in the proguard rules did the job for me

`-keep class com.facebook.jni.** { *; }`
`-keep class com.facebook.react.modules.blob.BlobCollector`
`-keep class com.squareup.duktape.** { *; }`
`-keep class com.facebook.hermes.reactexecutor.HermesExecutor`
