### ISSUE TITLE
Type com.facebook.react.bridge.Arguments is defined multiple times

### ISSUE THREAD

**Issue by sajanyamaha** [gunschu/jitsi_meet#251]
**jitsi_meet plugin version**
jitsi_meet: ^2.1.0

**Describe the bug**
Build is failing with the below Error ,

Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type com.facebook.react.bridge.Arguments is defined multiple times: /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/e95a010dbf19f527b2eabc0bfcc8953d80eb500c44576381683fda651d695b09_1.jar:classes.dex, /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/f6a4b6ec5fb4f3487380a10a6374f11e4cfbcb60c6060658f7213ac780642ecf_1.jar:classes.dex

**Detailed error**
```
Type com.facebook.react.bridge.Arguments is defined multiple times: /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/e95a010dbf19f527b2eabc0bfcc8953d80eb500c44576381683fda651d695b09_1.jar:classes.dex, /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/f6a4b6ec5fb4f3487380a10a6374f11e4cfbcb60c6060658f7213ac780642ecf_1.jar:classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:432)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/e95a010dbf19f527b2eabc0bfcc8953d80eb500c44576381683fda651d695b09_1.jar:classes.dex
	at Version.fakeStackEntry(Version_2.1.86.java:0)
	at com.android.tools.r8.utils.Y.a(SourceFile:78)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	... 33 more
Caused by: com.android.tools.r8.utils.b: Type com.facebook.react.bridge.Arguments is defined multiple times: /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/e95a010dbf19f527b2eabc0bfcc8953d80eb500c44576381683fda651d695b09_1.jar:classes.dex, /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/f6a4b6ec5fb4f3487380a10a6374f11e4cfbcb60c6060658f7213ac780642ecf_1.jar:classes.dex
	at com.android.tools.r8.utils.T0.error(SourceFile:1)
	at com.android.tools.r8.utils.T0.a(SourceFile:2)
	at com.android.tools.r8.utils.R0.b(SourceFile:6)
	at com.android.tools.r8.utils.R0.a(SourceFile:24)
	at com.android.tools.r8.utils.R0.a(SourceFile:10)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.R0.a(SourceFile:6)
	at com.android.tools.r8.graph.Q0$c.f(SourceFile:3)
	at com.android.tools.r8.dex.a.a(SourceFile:298)
	at com.android.tools.r8.dex.a.a(SourceFile:226)
	at com.android.tools.r8.D8.d(D8.java:6)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.Y.a(SourceFile:36)
	... 35 more
```
**Already tried**
```
./gradlew clean and
flutter clean
```

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/sajansj/Developer/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sajansj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/sajansj/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/sajansj/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM N950F (mobile) • 988ad036454256553830 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 89.0.4389.128

**Comment by sajanyamaha** [comment]
finally after full project overhaul ,upgraded to jitsi latest version `jitsi_meet: ^4.0.0` , Build fails ,same error , please help to sort this out .
```
Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Type com.facebook.react.bridge.Arguments is defined multiple times: /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/0fa753734c11180f0c66e8d40e3b0cf50626b9dcb55b5e928e938378a3bba487_1.jar:classes.dex, /Users/sajansj/StudioProjects/inhouse/build/app/intermediates/mixed_scope_dex_archive/debug/out/bd9a636f7a360923dfd668ed5ab54afb4dfefee66fb0a9e0af8bc0f4a884099e_1.jar:classes.dex
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```
