### ISSUE TITLE
[BUG]: JoinMeeting screen crashing with error

### ISSUE THREAD

**Issue by JankiGandhi0603** [gunschu/jitsi_meet#261]
**jitsi_meet :2.0.0**

**Describe the bug**
screen for join meeting appears and then crashes.

**Gradle version: 3.6.3 **

**Screenshots**

**Flutter doctor -v**
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
    • Flutter version 2.0.4 at E:\Android\flutter
    • Framework revision b1395592de (5 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Android\tools\SDK\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = E:\Android\tools\SDK\
    • ANDROID_SDK_ROOT = E:\Android\tools\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Janki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Nokia 7 2 (mobile) • J0AA002437J82902752 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)         • edge                • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```

**Web (please complete the following information):**
 - OS: [e.g. Mac, Windows, Linux]

**Smartphone (please complete the following information):**
 - Physical or Emulator

**Additional context**

**Error Logs**
```
D/ReactNative( 8166): ReactInstanceManager.setupReactContext()
D/ReactNative( 8166): CatalystInstanceImpl.initialize()
D/ReactNative( 8166): ReactInstanceManager.attachRootViewToInstance()
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater( 8166): Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
E/AndroidRuntime( 8166): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 8166): Process: com.eduauraa.eduauraaapp, PID: 8166
E/AndroidRuntime( 8166): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
E/AndroidRuntime( 8166):        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
E/AndroidRuntime( 8166):        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
E/AndroidRuntime( 8166):        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
E/AndroidRuntime( 8166):        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
E/AndroidRuntime( 8166):        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
E/AndroidRuntime( 8166):        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
E/AndroidRuntime( 8166):        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
E/AndroidRuntime( 8166):        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
E/AndroidRuntime( 8166):        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
E/AndroidRuntime( 8166):        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
E/AndroidRuntime( 8166):        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
E/AndroidRuntime( 8166):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8166):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E/AndroidRuntime( 8166):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8166):        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E/AndroidRuntime( 8166):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime( 8166): Caused by: java.lang.ClassNotFoundException: androidx.swiperefreshlayout.widget.SwipeRefreshLayout
E/AndroidRuntime( 8166):        at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 8166):        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 8166):        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 8166):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8166):        ... 22 more
E/AndroidRuntime( 8166): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/NestedScrollingParent3;
E/AndroidRuntime( 8166):        ... 22 more
E/AndroidRuntime( 8166): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.NestedScrollingParent3" on path: DexPathList[[zip file "/data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3ad
pxuh6GEp6eQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3adpxuh6GEp6eQ==/lib/arm64, /data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3adpxuh6GEp6eQ==/base.apk!/lib/arm64-v8a, /sy
stem/lib64, /system/product/lib64]]
E/AndroidRuntime( 8166):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime( 8166):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8166):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8166):        ... 22 more
E/JitsiMeetSDK( 8166): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 8166): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
E/JitsiMeetSDK( 8166):  at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
E/JitsiMeetSDK( 8166):  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
E/JitsiMeetSDK( 8166):  at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
E/JitsiMeetSDK( 8166):  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
E/JitsiMeetSDK( 8166):  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
E/JitsiMeetSDK( 8166):  at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
E/JitsiMeetSDK( 8166):  at android.os.Handler.handleCallback(Handler.java:883)
E/JitsiMeetSDK( 8166):  at android.os.Handler.dispatchMessage(Handler.java:100)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E/JitsiMeetSDK( 8166):  at android.os.Looper.loop(Looper.java:214)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E/JitsiMeetSDK( 8166):  at java.lang.Thread.run(Thread.java:919)
E/JitsiMeetSDK( 8166): Caused by: java.lang.ClassNotFoundException: androidx.swiperefreshlayout.widget.SwipeRefreshLayout
E/JitsiMeetSDK( 8166):  at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/JitsiMeetSDK( 8166):  at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/JitsiMeetSDK( 8166):  at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/JitsiMeetSDK( 8166):  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JitsiMeetSDK( 8166):  ... 22 more
E/JitsiMeetSDK( 8166): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/NestedScrollingParent3;
E/JitsiMeetSDK( 8166):  ... 22 more
E/JitsiMeetSDK( 8166): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.NestedScrollingParent3" on path: DexPathList[[zip file "/data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3adpx
uh6GEp6eQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3adpxuh6GEp6eQ==/lib/arm64, /data/app/com.eduauraa.eduauraaapp-6Tg8YPaC3adpxuh6GEp6eQ==/base.apk!/lib/arm64-v8a, /syst
em/lib64, /system/product/lib64]]
E/JitsiMeetSDK( 8166):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/JitsiMeetSDK( 8166):  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/JitsiMeetSDK( 8166):  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JitsiMeetSDK( 8166):  ... 22 more
E/JitsiMeetSDK( 8166):
E/JitsiMeetSDK( 8166): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
E/JitsiMeetSDK( 8166):  at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
E/JitsiMeetSDK( 8166):  at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
E/JitsiMeetSDK( 8166):  at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
E/JitsiMeetSDK( 8166):  at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
E/JitsiMeetSDK( 8166):  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
E/JitsiMeetSDK( 8166):  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
E/JitsiMeetSDK( 8166):  at com.facebook.react.bridge.CatalystInsta
```

## Proguard pro file 
```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**
-keep class com.shockwave.**

## flutter_local_notification plugin rules
-keep class com.dexterous.** { *; }

## Gson rules
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}


#=== Jitsi ===#
# Source: https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro
# Check above link for changes if release builds are broken again

# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-keep class okio.** { *; }
-dontwarn okio.**

# WebRTC

-keep class org.webrtc.** { *; }
-dontwarn org.chromium.build.BuildHooksAndroid

# Jisti Meet SDK

-keep class org.jitsi.meet.** { *; }
-keep class org.jitsi.meet.sdk.** { *; }

# We added the following when we switched minifyEnabled on. Probably because we
# ran the app and hit problems...

-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.devsupport.** { *; }

-dontwarn com.facebook.react.devsupport.**
-dontwarn com.google.appengine.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.servlet.**

# ^^^ We added the above when we switched minifyEnabled on.

# Rule to avoid build errors related to SVGs.
-keep public class com.horcrux.svg.** {*;}

# Hermes
-keep class com.facebook.hermes.unicode.** { *; }
```

**Comment by Manjunath-VM** [comment]
@JankiGandhi0603 did u got any solution i am facing the same issue

**Comment by JankiGandhi0603** [comment]
> @JankiGandhi0603 did u got any solution i am facing the same issue

yes I got solution. it is issue related to flutter dependency material  version and  jitsi meet (version conflict issue)
downgrades jitsi meet version.
