### ISSUE TITLE
[BUG]: App crash when leaving the conference

### ISSUE THREAD

**Issue by pulstar** [gunschu/jitsi_meet#284]
**jitsi_meet plugin version**
jitsi_meet: ^4.0.0

**Describe the bug**
App crash when leaving the conference.

**To Reproduce**
1. Participants enter the conference
2. Remote participant leaves the conference with no error
3. Local participant leave the conference then the app crashes

**Flutter doctor -v**
```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.1083], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (5 available)
    • Vivo XI (mobile)     • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Moto X Play (mobile) • ZY223DPJLM       • android-arm    • Android 7.1.1 (API 25)
    • Windows (desktop)    • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1083]
    • Chrome (web)         • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)           • edge             • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.
```

**Smartphone (please complete the following information):**
 - Device: Moto X Play
 - Physical or Emulator: physical
 - OS: Android
 - Version: 7.1.1

**Error Logs**
```
D/AndroidRuntime( 9827): Shutting down VM
E/JitsiMeetSDK( 9827): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 9827): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetPluginActivity Paused activity: JitsiMeetPluginActivity
E/JitsiMeetSDK( 9827): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
E/JitsiMeetSDK( 9827): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
E/JitsiMeetSDK( 9827): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:124)
E/JitsiMeetSDK( 9827): 	at org.jitsi.meet.sdk.JitsiMeetFragment.onStop(JitsiMeetFragment.java:78)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.Fragment.performStop(Fragment.java:2895)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:391)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1223)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2610)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
E/JitsiMeetSDK( 9827): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onStop(JitsiMeetPluginActivity.kt:61)
E/JitsiMeetSDK( 9827): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1311)
E/JitsiMeetSDK( 9827): 	at android.app.Activity.performStop(Activity.java:6862)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4201)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4262)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
E/JitsiMeetSDK( 9827): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/JitsiMeetSDK( 9827): 	at android.os.Looper.loop(Looper.java:154)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
E/JitsiMeetSDK( 9827): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 9827): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
E/JitsiMeetSDK( 9827): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
E/JitsiMeetSDK( 9827): 
E/JitsiMeetSDK( 9827): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetPluginActivity Paused activity: JitsiMeetPluginActivity
E/JitsiMeetSDK( 9827): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
E/JitsiMeetSDK( 9827): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
E/JitsiMeetSDK( 9827): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:124)
E/JitsiMeetSDK( 9827): 	at org.jitsi.meet.sdk.JitsiMeetFragment.onStop(JitsiMeetFragment.java:78)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.Fragment.performStop(Fragment.java:2895)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:391)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1223)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2610)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
E/JitsiMeetSDK( 9827): 	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
E/JitsiMeetSDK( 9827): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onStop(JitsiMeetPluginActivity.kt:61)
E/JitsiMeetSDK( 9827): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1311)
E/JitsiMeetSDK( 9827): 	at android.app.Activity.performStop(Activity.java:6862)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4201)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4262)
E/JitsiMeetSDK( 9827): 	at android.app.ActivityThread.-wrap6(ActivityThrea
E/AndroidRuntime( 9827): FATAL EXCEPTION: main
E/AndroidRuntime( 9827): Process: br.com.gdiac.interfone, PID: 9827
E/AndroidRuntime( 9827): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetPluginActivity Paused activity: JitsiMeetPluginActivity
E/AndroidRuntime( 9827): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
E/AndroidRuntime( 9827): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
E/AndroidRuntime( 9827): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:124)
E/AndroidRuntime( 9827): 	at org.jitsi.meet.sdk.JitsiMeetFragment.onStop(JitsiMeetFragment.java:78)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.Fragment.performStop(Fragment.java:2895)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:391)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1223)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:2610)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:291)
E/AndroidRuntime( 9827): 	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:563)
E/AndroidRuntime( 9827): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onStop(JitsiMeetPluginActivity.kt:61)
E/AndroidRuntime( 9827): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1311)
E/AndroidRuntime( 9827): 	at android.app.Activity.performStop(Activity.java:6862)
E/AndroidRuntime( 9827): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4201)
E/AndroidRuntime( 9827): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4262)
E/AndroidRuntime( 9827): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/AndroidRuntime( 9827): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
E/AndroidRuntime( 9827): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9827): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 9827): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
E/AndroidRuntime( 9827): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9827): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
E/AndroidRuntime( 9827): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
D/TransportRuntime.SQLiteEventStore( 9827): Storing event with priority=DEFAULT, name=FIREPERF for destination cct
D/TransportRuntime.JobInfoScheduler( 9827): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) with jobId=2017800497 in 30000ms(Backend next call timestamp 1626268695113). Attempt 1
I/JitsiMeetSDK( 9827): [features/base/lib-jitsi-meet] Config loaded from https://meet.jit.si/config.js?room=com_eboreah_interfone_fq1wjsteq299
I/JitsiMeetSDK( 9827): [features/base/config] Extending config with: {"startAudioOnly":false,"startWithAudioMuted":true,"startWithVideoMuted":false,"subject":"Conference"}
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
D/JitsiMeetSDK( 9827): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
I/JitsiMeetSDK( 9827): [features/analytics] Initialized 1 analytics handlers
I/JitsiMeetSDK( 9827): [features/base/media] Start muted: audio, 
D/JitsiMeetSDK( 9827): ExternalAPI Sending event: AUDIO_MUTED_CHANGED with data: { NativeMap: {"muted":true} }
D/JitsiMeetSDK( 9827): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK( 9827): [features/base/media] Start audio only set to false
D/JitsiMeetSDK( 9827): ExternalAPI Sending event: CONFERENCE_WILL_JOIN with data: { NativeMap: {"url":"https://meet.jit.si/com_eboreah_interfone_FQ1WJSTEQ299"} }
I/JitsiMeetSDK( 9827): [modules/xmpp/xmpp.js] P2P STUN servers:  [ { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' } ]
I/JitsiMeetSDK( 9827): [modules/xmpp/xmpp.js] (TIME) Strophe connecting:	 1626268716904
I/JitsiMeetSDK( 9827): [modules/RTC/RTCUtils.js] Get media constraints {"audio":false,"video":{"mandatory":{"minWidth":1280,"minHeight":720,"maxWidth":1280,"maxHeight":720},"optional":[{"facingMode":"user"}],"facingMode":"user","width":{"ideal":1280},"height":{"ideal":720}}}
D/JitsiMeetSDK( 9827): [modules/RTC/RTCUtils.js] Available devices:  [ { kind: 'videoinput',
D/JitsiMeetSDK( 9827):     label: 'Camera 0, Facing back, Orientation 90',
D/JitsiMeetSDK( 9827):     groupId: '',
D/JitsiMeetSDK( 9827):     deviceId: '0',
D/JitsiMeetSDK( 9827):     facing: 'environment' },
D/JitsiMeetSDK( 9827):   { kind: 'videoinput',
D/JitsiMeetSDK( 9827):     label: 'Camera 1, Facing front, Orientation 270',
D/JitsiMeetSDK( 9827):     groupId: '',
D/JitsiMeetSDK( 9827):     deviceId: '1',
D/JitsiMeetSDK( 9827):     facing: 'front' },
D/JitsiMeetSDK( 9827):   { kind: 'audioinput',
D/JitsiMeetSDK( 9827):     label: 'Audio',
D/JitsiMeetSDK( 9827):     groupId: '',
D/JitsiMeetSDK( 9827):     deviceId: 'audio-1' } ]
D/com.oney.WebRTCModule.WebRTCModule( 9827): getUserMedia(video): { NativeMap: {"facingMode":"user","frameRate":30,"height":720,"width":1280} }
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
D/CameraCaptureController( 9827): Create camera Camera 1, Facing front, Orientation 270 succeeded
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 9827): CameraCapturer: startCapture: 1280x720@30
I/org.webrtc.Logging( 9827): Camera1Session: Open camera Camera 1, Facing front, Orientation 270
D/com.oney.WebRTCModule.WebRTCModule( 9827): CameraEventsHandler.onCameraOpening: cameraName=Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
D/com.oney.WebRTCModule.WebRTCModule( 9827): MediaStream id: 9eeea46f-40fe-4eb5-9164-4063207611c5
I/JitsiMeetSDK( 9827): [modules/RTC/RTCUtils.js] onUserMediaSuccess
D/JitsiMeetSDK( 9827): [modules/RTC/JitsiLocalTrack.js] Setting new MSID: 24f3e039-6f23-4114-ab63-357086c1e325 8db4d141-5f2d-4142-86a4-ee61b320e83e on LocalTrack[undefined,video]
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 270
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90
I/org.webrtc.Logging( 9827): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 270
I/JitsiMeetSDK( 9827): [features/base/redux] redux state persisted. 3576686087039426db1da390d4276544 -> 4540501dec3fb5289bbb233e7c25b089
I/org.webrtc.Logging( 9827): Camera1Session: Available fps ranges: [[15.0:15.0], [15.0:30.0], [24.0:30.0], [30.0:30.0]]
I/org.webrtc.Logging( 9827): Camera1Session: Create new camera1 session on camera 1
I/org.webrtc.Logging( 9827): Camera1Session: Start capturing
I/org.webrtc.Logging( 9827): CameraCapturer: Create session done. Switch state: IDLE
D/com.oney.WebRTCModule.WebRTCModule( 9827): CameraEventsHandler.onFirstFrameAvailable
W/JitsiMeetSDK( 9827): [modules/xmpp/XmppConnection.js] Stream resume enabled, but WebSockets are not enabled
I/JitsiMeetSDK( 9827): [modules/xmpp/strophe.ping.js] XMPP pings will be sent every 10000 ms
I/JitsiMeetSDK( 9827): [modules/xmpp/xmpp.js] (TIME) Strophe connected:	 1626268718659
I/JitsiMeetSDK( 9827): [modules/xmpp/xmpp.js] My Jabber ID: 803d5628-721f-4bfb-8fc5-386c491f3a49@meet.jit.si/OdhFsTP1
D/JitsiMeetSDK( 9827): [modules/RTC/CodecSelection.js] Codec preferences for the conference are JVB: vp8,
D/JitsiMeetSDK( 9827):             P2P: h264
I/JitsiMeetSDK( 9827): [modules/xmpp/xmpp.js] JID 803d5628-721f-4bfb-8fc5-386c491f3a49@meet.jit.si/OdhFsTP1 using MUC nickname 803d5628
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] Joined MUC as com_eboreah_interfone_fq1wjsteq299@conference.meet.jit.si/803d5628
I/JitsiMeetSDK( 9827): [modules/e2eping/e2eping.js] Initializing e2e ping; pingInterval=-1, analyticsInterval=60000.
I/JitsiMeetSDK( 9827): [modules/connectivity/ParticipantConnectionStatus.js] RtcMuteTimeout set to: 10000
W/JitsiMeetSDK( 9827): [JitsiConference.js] No VAD Processor was provided. Talk while muted detection service was not initialized!
W/JitsiMeetSDK( 9827): [JitsiConference.js] No VAD Processor was provided. Noisy microphone detection service was not initialized!
D/JitsiMeetSDK( 9827): [modules/qualitycontrol/ReceiveVideoController.js] Updating ReceiverVideoConstraints lastN(20)
I/JitsiMeetSDK( 9827): [modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
I/JitsiMeetSDK( 9827): [JitsiConference.js] backToP2PDelay: 5
D/JitsiMeetSDK( 9827): [modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW
I/JitsiMeetSDK( 9827): [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
I/JitsiMeetSDK( 9827): [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
D/JitsiMeetSDK( 9827): [features/base/lastn] There is no active conference, not updating last N
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] Focus jid set to:  undefined
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] Session ID: null machine UID: a17e333ab8d451688d141fa907d3be8a
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 29.
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] Focus jid set to:  focus@auth.meet.jit.si
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] Authentication enabled: false
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] External authentication enabled: false
I/JitsiMeetSDK( 9827): [modules/xmpp/moderator.js] Sip gateway enabled:  false
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] entered com_eboreah_interfone_fq1wjsteq299@conference.meet.jit.si/focus { affiliation: 'owner',
I/JitsiMeetSDK( 9827):   role: 'moderator',
I/JitsiMeetSDK( 9827):   jid: 'focus@auth.meet.jit.si/focus',
I/JitsiMeetSDK( 9827):   isFocus: true,
I/JitsiMeetSDK( 9827):   isHiddenDomain: false }
I/JitsiMeetSDK( 9827): [modules/version/ComponentsVersions.js] Got focus version: 1.0.765
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] Jicofo supports restart by terminate: true
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] (TIME) MUC joined:	 1626268720688
I/JitsiMeetSDK( 9827): [features/video-quality] setReceiverVideoConstraint: 2160
D/JitsiMeetSDK( 9827): ExternalAPI Sending event: CONFERENCE_JOINED with data: { NativeMap: {"url":"https://meet.jit.si/com_eboreah_interfone_FQ1WJSTEQ299"} }
I/JitsiMeetSDK( 9827): AudioMode Update audio route for mode: 2
D/JitsiMeetSDK( 9827): [JitsiConference.js] P2P? peerCount: 0, hasBotPeer: false => false
I/JitsiMeetSDK( 9827): AudioMode Selected audio device: SPEAKER
I/JitsiMeetSDK( 9827): AudioMode Updating audio device list
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] Subject is changed to 
I/JitsiMeetSDK( 9827): [modules/xmpp/ChatRoom.js] Subject is changed to Conference
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
I/FirebaseAuth( 9827): [FirebaseAuth:] Preparing to create service connection to fallback implementation
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 30.
I/org.webrtc.Logging( 9827): CameraStatistics: Camera fps: 31.
Lost connection to device.
```

**Comment by thananat-dev** [comment]
I have same problem.
