### ISSUE TITLE
[BUG]: App crashed when terminating call

### ISSUE THREAD

**Issue by marcoberetta96** [gunschu/jitsi_meet#325]
**jitsi_meet plugin version**
jitsi_meet: 4.0.0

**Describe the bug**
Call works normally, but the app always crashes when terminating call

**To Reproduce**
- start a new call
- stay in the call as much as you want
- terminate the call

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.5.2, on Ubuntu 20.04.3 LTS 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/marco/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 948AY0KK49 • android-arm64 • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64     • Ubuntu 20.04.3 LTS 5.11.0-37-generic

**Smartphone:**
 - Pixel 3a, Android 11

**Error Logs**
```
I/JitsiMeetSDK(11560): [features/base/redux] redux state persisted. c845f59756b68b678cbc4b163b5e20b6 -> 71c59386afe2723bda06fd62fb54932a
D/JitsiMeetSDK(11560): [features/base/lastn] There is no active conference, not updating last N
I/JitsiMeetSDK(11560): [modules/e2eping/e2eping.js] Stopping e2eping
I/JitsiMeetSDK(11560): [modules/xmpp/ChatRoom.js] do leave vggg@conference.jitsi.enerlamp.it/8179ac8e
I/org.webrtc.Logging(11560): CameraStatistics: Camera fps: 25.
I/org.webrtc.Logging(11560): SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1074x2082
I/org.webrtc.Logging(11560): EglRenderer: setLayoutAspectRatio: 0.5158501
D/JitsiMeetSDK(11560): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
I/JitsiMeetSDK(11560): [features/analytics] Initialized 1 analytics handlers
I/JitsiMeetSDK(11560): [features/base/media] Start muted: 
D/JitsiMeetSDK(11560): ExternalAPI Sending event: AUDIO_MUTED_CHANGED with data: { NativeMap: {"muted":false} }
D/JitsiMeetSDK(11560): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(11560): JitsiMeetOngoingConferenceService Service started
I/JitsiMeetSDK(11560): [features/base/media] Start audio only set to false
E/.my_app(11560): No package ID ff found for ID 0xffffffff.
I/org.webrtc.Logging(11560): EglRenderer: setMirrorHorizontally: true
E/ThemeUtils(11560): View class com.facebook.react.views.text.ReactTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(11560): View class com.facebook.react.views.switchview.ReactSwitch is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/unknown:ViewManager(11560): Error while updating prop thumbTintColor
E/unknown:ViewManager(11560): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/unknown:ViewManager(11560): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/unknown:ViewManager(11560): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/unknown:ViewManager(11560): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ViewManager(11560): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
E/unknown:ViewManager(11560): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/unknown:ViewManager(11560): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
E/unknown:ViewManager(11560): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/unknown:ViewManager(11560): 	at android.os.Handler.handleCallback(Handler.java:938)
E/unknown:ViewManager(11560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/unknown:ViewManager(11560): 	at android.os.Looper.loop(Looper.java:223)
E/unknown:ViewManager(11560): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/unknown:ViewManager(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(11560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/unknown:ViewManager(11560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/unknown:ViewManager(11560): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/unknown:ViewManager(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/unknown:ViewManager(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/unknown:ViewManager(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/unknown:ViewManager(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/unknown:ViewManager(11560): 	... 23 more
D/AndroidRuntime(11560): Shutting down VM
E/AndroidRuntime(11560): FATAL EXCEPTION: main
E/AndroidRuntime(11560): Process: com.marco.my_app, PID: 11560
E/AndroidRuntime(11560): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/AndroidRuntime(11560): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/AndroidRuntime(11560): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/AndroidRuntime(11560): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
E/AndroidRuntime(11560): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/AndroidRuntime(11560): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
E/AndroidRuntime(11560): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/AndroidRuntime(11560): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(11560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11560): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(11560): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(11560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(11560): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/AndroidRuntime(11560): 	... 21 more
E/AndroidRuntime(11560): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/AndroidRuntime(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/AndroidRuntime(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/AndroidRuntime(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/AndroidRuntime(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/AndroidRuntime(11560): 	... 23 more
E/JitsiMeetSDK(11560): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(11560): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/JitsiMeetSDK(11560): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/JitsiMeetSDK(11560): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/JitsiMeetSDK(11560): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK(11560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(11560): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(11560): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/JitsiMeetSDK(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(11560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(11560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(11560): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/JitsiMeetSDK(11560): 	... 21 more
E/JitsiMeetSDK(11560): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/JitsiMeetSDK(11560): 	... 23 more
E/JitsiMeetSDK(11560): 
E/JitsiMeetSDK(11560): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/JitsiMeetSDK(11560): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/JitsiMeetSDK(11560): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
E/JitsiMeetSDK(11560): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/JitsiMeetSDK(11560): 	at android.os.Handler.handleCallback(Handler.java:938)
E/JitsiMeetSDK(11560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(11560): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(11560): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/JitsiMeetSDK(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(11560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(11560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(11560): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK(11560): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(11560): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/JitsiMeetSDK(11560): 	... 21 more
E/JitsiMeetSDK(11560): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/JitsiMeetSDK(11560): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/JitsiMeetSDK(11560): 	... 23 more
E/ThemeUtils(11560): View class com.facebook.react.views.switchview.ReactSwitch is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/.my_app(11560): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/JitsiMeetSDK(11560): [features/calendar-sync] Calendar access not granted.
D/JitsiMeetSDK(11560): [modules/RTC/RTCUtils.js] Available devices:  [ { kind: 'videoinput',
D/JitsiMeetSDK(11560):     label: '0',
D/JitsiMeetSDK(11560):     groupId: '',
D/JitsiMeetSDK(11560):     deviceId: '0',
D/JitsiMeetSDK(11560):     facing: 'environment' },
D/JitsiMeetSDK(11560):   { kind: 'videoinput',
D/JitsiMeetSDK(11560):     label: '1',
D/JitsiMeetSDK(11560):     groupId: '',
D/JitsiMeetSDK(11560):     deviceId: '1',
D/JitsiMeetSDK(11560):     facing: 'front' },
D/JitsiMeetSDK(11560):   { kind: 'audioinput',
D/JitsiMeetSDK(11560):     label: 'Audio',
D/JitsiMeetSDK(11560):     groupId: '',
D/JitsiMeetSDK(11560):     deviceId: 'audio-1' } ]
I/JitsiMeetSDK(11560): JitsiMeetOngoingConferenceServiceService stopped
D/JitsiMeetSDK(11560): ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://jitsi.enerlamp.it/vggg"} }
I/JitsiMeetSDK(11560): AudioMode Update audio route for mode: 0
I/JitsiMeetSDK(11560): [modules/xmpp/xmpp.js] (TIME) Strophe disconnecting:	 1634766899409
I/JitsiMeetSDK(11560): AudioMode Updating audio device list
I/JitsiMeetSDK(11560): [modules/xmpp/strophe.ping.js] Ping interval cleared
I/JitsiMeetSDK(11560): [modules/xmpp/xmpp.js] (TIME) Strophe disconnected:	 1634766899598
I/org.webrtc.Logging(11560): CameraStatistics: Camera fps: 25.
I/org.webrtc.Logging(11560): EglRenderer: Duration: 4001 ms. Frames received: 100. Dropped: 0. Rendered: 100. Render fps: 25,0. Average render time: 2626 us. Average swapBuffer time: 1206 us.
I/org.webrtc.Logging(11560): CameraStatistics: Camera fps: 25.
E/FirebaseCrashlytics(11560): Error handling uncaught exception
E/FirebaseCrashlytics(11560): java.util.concurrent.TimeoutException
E/FirebaseCrashlytics(11560): 	at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:122)
E/FirebaseCrashlytics(11560): 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:232)
E/FirebaseCrashlytics(11560): 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:155)
E/FirebaseCrashlytics(11560): 	at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:54)
E/FirebaseCrashlytics(11560): 	at org.jitsi.meet.sdk.JitsiMeetUncaughtExceptionHandler.uncaughtException(JitsiMeetUncaughtExceptionHandler.java:48)
E/FirebaseCrashlytics(11560): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/FirebaseCrashlytics(11560): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/FirebaseCrashlytics(11560): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
I/Process (11560): Sending signal. PID: 11560 SIG: 9
Lost connection to device.


```

**Comment by DenisMrGnusa** [comment]
same issue here..

**Comment by ducnmhn** [comment]
I don't know why but we need turn off WELCOME_PAGE_ENABLED to fix it

`  Map<FeatureFlagEnum, bool> featureFlags = {
      FeatureFlagEnum.WELCOME_PAGE_ENABLED: false,
    };`

**Comment by ahmadzt** [comment]
> I don't know why but we need turn off WELCOME_PAGE_ENABLED to fix it
> 
> ` Map<FeatureFlagEnum, bool> featureFlags = { FeatureFlagEnum.WELCOME_PAGE_ENABLED: false, };`

Yes, setting `WELCOME_PAGE_ENABLED: false` does fix the issue
