### ISSUE TITLE
[UPGRADE]: org.jitsi.meet.sdk.ConnectionService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

### ISSUE THREAD

**Issue by sayanlp99** [gunschu/jitsi_meet#356]
**Dependency Information**
Name:
Version:
Platform
* [x] Android
* [ ] iOS
* [ ] Web 

**Reason for upgrade**
When I am running my project on Android 12 it shows an error that it android:exported is required in org.jitsi.meet.sdk.ConnectionService but this activity is not present in AndroidManifest.xml

**Provide additional context*
![Screenshot 2022-02-15 015526](https://user-images.githubusercontent.com/28763093/153940823-fac65935-1958-4fe5-8e9f-21b654589926.png)

**Comment by MushtaqAlabbasi** [comment]
I have the same issue too

**Comment by TarishAhmed** [comment]
try setting target SDK version to 30 and compile SDK version to 31, this is only a temporary fix
    `android {
    compileSdkVersion 31
    defaultConfig {
        // ...
        minSdkVersion 23 //Required for Jitsi
        targetSdkVersion 30
        // ...
    }
}`

**Comment by minh-dai** [comment]
in my flutter project, It has the same error

**Comment by Meri994** [comment]
@TarishAhmed I am facing the same issue.
https://github.com/gunschu/jitsi_meet/issues/366

your temporary given solution is working for me but it is not accurate. Did you find any other solution?

**Comment by Imperial-lord** [comment]
This issue needs attention. I am facing the same thing as well!

**Comment by Harishwarrior** [comment]
Can I work on this or is it already assigned?

**Comment by Meri994** [comment]
@Harishwarrior Hey, Please check it from your end. Give support to the latest android version.

**Comment by Harishwarrior** [comment]
> @Harishwarrior Hey, Please check it from your end. Give support to the latest android version.

Awesome. I'll work on it right now.

**Comment by Meri994** [comment]
> > @Harishwarrior Hey, Please check it from your end. Give support to the latest android version.
> 
> Awesome. I'll work on it right now.

Thanks

**Comment by Harishwarrior** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gunschu.jitsi_meet_example/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(17133): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
E/AndroidRuntime(17133): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
E/AndroidRuntime(17133): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(17133): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17133): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17133): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
E/AndroidRuntime(17133): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17133): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17133): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17133): 	at android.app.ActivityThread.main(ActivityThread.java:7835)
E/AndroidRuntime(17133): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17133): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17133): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(17133): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(17133): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime(17133): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime(17133): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
E/AndroidRuntime(17133): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
E/AndroidRuntime(17133): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:81)
E/AndroidRuntime(17133): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/AndroidRuntime(17133): 	at android.app.Activity.performCreate(Activity.java:8050)
E/AndroidRuntime(17133): 	at android.app.Activity.performCreate(Activity.java:8030)
E/AndroidRuntime(17133): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
E/AndroidRuntime(17133): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
E/AndroidRuntime(17133): 	... 12 more
I/Process (17133): Sending signal. PID: 17133 SIG: 9

```

@tuantvu I have migrated this plugin. But, when I press start meeting the app crashes.

**Comment by RajChavda** [comment]
@Harishwarrior This is the same problem we are facing and a black screen appears on some Android devices. 

Thanks in advance for your help.

**Comment by Meri994** [comment]
@jimmyjose-dev  Check this if you can help us. Thank you.

**Comment by Harishwarrior** [comment]
> @Harishwarrior This is the same problem we are facing and a black screen appears on some Android devices. 
> 
> Thanks in advance for your help.

Seems like we need to change implementation part. Lemme try fixing it.

**Comment by RajChavda** [comment]
> > @Harishwarrior This is the same problem we are facing and a black screen appears on some Android devices.
> > Thanks in advance for your help.
> 
> Seems like we need to change implementation part. Lemme try fixing it.

Okay, I understand but it would be great if you could tell us when it will be completed.

**Comment by Harishwarrior** [comment]
> > > @Harishwarrior This is the same problem we are facing and a black screen appears on some Android devices.
> > > Thanks in advance for your help.
> > 
> > Seems like we need to change implementation part. Lemme try fixing it.
> 
> Okay, I understand but it would be great if you could tell us when it will be completed.

Currently I have no solution. I'll work on it. Don't know when it'll be fixed. Cause I don't wanna do workarounds to fix this temporarily.

**Comment by MusabBoltX** [comment]
![error](https://user-images.githubusercontent.com/68772934/159423014-edeb3569-72d3-4e7a-b2b4-b5bcdf535e0a.PNG)
 Still I'm facing the issue on production can someone please tell the issue temporarily that i can give app to production thanks in advance

**Comment by TarishAhmed** [comment]
> ![error](https://user-images.githubusercontent.com/68772934/159423014-edeb3569-72d3-4e7a-b2b4-b5bcdf535e0a.PNG) Still I'm facing the issue on production can someone please tell the issue temporarily that i can give app to production thanks in advance

https://github.com/gunschu/jitsi_meet/issues/356#issuecomment-1049706019

Try this.

**Comment by VasuVaradhan** [comment]
May I get any solution other than the temporary fixes

**Comment by edx86** [comment]
Hi, based on exception looks like you have to add android:exported="true" to android manifest.

Can you please make sure that you have added it to app/src/main/AndroidManifest.xml ?
```xml
<application
    ...
    <activity
        ...
        android:exported="true"
        ....
```

I am not sure this may resolve the issue, but give it a try.

**Comment by subhra9326** [comment]
Hi, I am also facing the same issue after upgrading flutter 3.0
All the packages are working well but when I add this jitsimeet packages it gives an error same as the title given here.
I have already added the android:exported="true" in AndroidManifest but still, it gives an error. Please fix this issue and update the AndroidManifest used in this packakges.

**Comment by alabbasiDev** [comment]
try using this package jitsi_meet_wrapper instead. it works fine for  me.

https://pub.dev/packages/jitsi_meet_wrapper

**Comment by definitelyme** [comment]
> try using this package jitsi_meet_wrapper instead. it works fine for me.
> 
> https://pub.dev/packages/jitsi_meet_wrapper

Works!
Use like this:
```yaml
jitsi_meet_wrapper:
  git:
    url: https://github.com/Flutter-Fox/jitsi_meet_wrapper.git
    path: jitsi_meet_wrapper/
    ref: fix/pubspec
```

**Comment by tushar-asodariya** [comment]
> try setting target SDK version to 30 and compile SDK version to 31, this is only a temporary fix `android { compileSdkVersion 31 defaultConfig { // ... minSdkVersion 23 //Required for Jitsi targetSdkVersion 30 // ... } }`

this worked

**Comment by myasir2** [comment]
I was having this problem with gradle 7 with one of my newer apps. It works perfectly fine on one of my older app which is using gradle 6. So I changed my gradle version to 6 and it started working. I changed it to 6.7 in the `gradle-wrapper.properties` file, and changed `com.android.tools.build:gradle` to `4.1.0`:

**build.gradle**
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**gradle-wrapper.properties**
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

**Comment by Eng-NUREDDIN** [comment]
use this in pubspec :
jitsi_meet:
    git:
      url: https://github.com/Eng-NUREDDIN/jitsi_meet.git
      path: jitsi_meet/
      ref: master

**Comment by habner12** [comment]
@Eng-NUREDDIN where should I put this? I put on Pubsec.yaml but still not working.

**Comment by ghost** [comment]
any updates ??

**Comment by Eng-NUREDDIN** [comment]
@habner12  sorry for the late response yes in the pubspec and it should work. what is the error you are getting?

**Comment by MAlazhariy** [comment]
This solution worked for me.

> add this service to your manifest

```
<service
       android:name="org.jitsi.meet.sdk.ConnectionService"
       android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE"
       android:exported="true">
       <intent-filter>
           <action android:name="android.telecom.ConnectionService" />
       </intent-filter>
</service>
```

reference: [https://stackoverflow.com/a/73272731/16449728](https://stackoverflow.com/a/73272731/16449728)

**Comment by habner12** [comment]
@Eng-NUREDDIN Thank you so much! Now My App it works. 👍

**Comment by Dewsworld** [comment]
@Eng-NUREDDIN your solution is working! Can you make it a standard package?

**Comment by sumit-coder** [comment]
Thanks, this is working, if want to where to add then [ add this in the manifest: manifest > application > after activity>add this ] from @MAlazhariy solution

**Comment by mh-sarkar-official** [comment]
> > try using this package jitsi_meet_wrapper instead. it works fine for me.
> > https://pub.dev/packages/jitsi_meet_wrapper
> 
> Works! Use like this:
> 
> ```yaml
> jitsi_meet_wrapper:
>   git:
>     url: https://github.com/Flutter-Fox/jitsi_meet_wrapper.git
>     path: jitsi_meet_wrapper/
>     ref: fix/pubspec
> ```

But this package has no terminated option programmatically!

**Comment by agustinmejia** [comment]
> Esta solución funcionó para mí.
> 
> > agregue este servicio a su manifiesto
> 
> ```
> <service
>        android:name="org.jitsi.meet.sdk.ConnectionService"
>        android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE"
>        android:exported="true">
>        <intent-filter>
>            <action android:name="android.telecom.ConnectionService" />
>        </intent-filter>
> </service>
> ```
> 
> referencia: https://stackoverflow.com/a/73272731/16449728

El problema es que aumenta 20 MB más a tu versión final y arroja varios errores en el informe de lanzamiento de google play console.

**Comment by koai-dev** [comment]
> Giải pháp này làm việc cho tôi.
> 
> > Thêm dịch vụ này vào tệp kê khai của bạn
> 
> ```
> <service
>        android:name="org.jitsi.meet.sdk.ConnectionService"
>        android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE"
>        android:exported="true">
>        <intent-filter>
>            <action android:name="android.telecom.ConnectionService" />
>        </intent-filter>
> </service>
> ```
> 
> Tham khảo: https://stackoverflow.com/a/73272731/16449728

thank you. It work for me

**Comment by bradfordcan** [comment]
Thank you for your workaround on this and it works if you use sdkVersion 30.  But Google requires us to publish 31.  Any updates on this?  We would like to use your solution but we might have to find another solution because of this.

**Comment by ndizihiwesimon** [comment]
I am still facing issue when I tap on join meeting and app crashes, I have tried to configure pro-guard.pro but it doesn't take effect! I am using jist_meet_wrapper, any fix?
Thank you

**Comment by MusabBoltX** [comment]
> I am still facing issue when I tap on join meeting and app crashes, I have tried to configure pro-guard.pro but it doesn't take effect! I am using jist_meet_wrapper, any fix? Thank you

Looks like the package has been discontinued and has been replaced with [jisti_meet_wrapper](https://pub.dev/packages/jitsi_meet_wrapper). Previously, I gave up on jitsi_meet because of no updates. Android 12+ devices where it crashes and you may try its wrapper package and go boom if it works on Android 12+.
